---
title: "Differential expression analysis in all cell types using mPAP"
author: "GinoBonazza (ginoandrea.bonazza@usz.ch)"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: inline
---

```{r knitr config, include=FALSE, cache=FALSE}
knitr::opts_chunk$set(warning = FALSE)

knitr::opts_chunk$set(message = FALSE)

knitr::opts_chunk$set(cache = FALSE)

knitr::opts_chunk$set(dpi = 300, fig.align = "center")
```

## Setup

```{r setup, class.source = "fold-hide"}
# Get current file name to make folder
current_file <- "DE_mPAP_all_cell_types"

# Load libraries
library(here)
library(dplyr)
library(ggplot2)
library(tibble)
library(readr)
library(readxl)
library(knitr)
library(patchwork)
library(scales)

library(clusterProfiler)
library(org.Hs.eg.db)
library(enrichplot)


library(Seurat)
library(DropletUtils)
library(Matrix)
library(scDblFinder)
library(scCustomize)
library(magrittr)
library(tidyverse)
library(reshape2)
library(S4Vectors)
library(SingleCellExperiment)
library(pheatmap)
library(png)
library(gridExtra)
library(Matrix.utils)
library(scater)
library(statmod)
library(clustree)
library(harmony)
library(gprofiler2)
library(AnnotationHub)
library(ReactomePA)
library(speckle)
library(limma)
library(reactable)
library(decoupleR)
library(OmnipathR)
library(dorothea)
library(edgeR)
library(rtracklayer)
library(EnhancedVolcano)
library(ComplexHeatmap)
library(cowplot)

#Output paths
output_dir_data <- here::here("output", current_file)
if (!dir.exists(output_dir_data)) dir.create(output_dir_data)

if (!dir.exists(here::here("docs", "figure"))) dir.create(here::here("docs", "figure"))

output_dir_figs <- here::here("docs", "figure", paste0(current_file, ".Rmd"))
if (!dir.exists(output_dir_figs)) dir.create(output_dir_figs)
```


## DE mPAP

Load seurat object

```{r read DCM_RV_integrated}
DCM_RV_integrated <- readRDS(here::here("output", "QC_integration_annotation", "DCM_RV.rds"))
```

Load DE results

```{r cluster_names}
cluster_names <- c("Cardiomyocytes", "Fibroblasts", "Endothelial_cells", "Pericytes", "Macrophages", "T_lymphocytes", "Smooth_muscle_cells", "Neuronal_cells", "Endocardial_cells")
```

```{r Load results}
results <- list()
for (i in seq_along(cluster_names)) {
  results[[i]] <- read.csv(here::here("output", "DA_DE_all_cell_types_and_parameters", paste0(cluster_names[i], "_DE_Results_mPAP_mmHg.csv")))
  names(results)[i] <- cluster_names[i]
}
```

```{r Load signif}
signif <- list()
for (i in seq_along(cluster_names)) {
  signif[[i]] <- read.csv(here::here("output", "DA_DE_all_cell_types_and_parameters", paste0(cluster_names[i], "_DE_Significant_mPAP_mmHg.csv")))
  names(signif)[i] <- cluster_names[i]
}
```

Add info to the results data frame: coding/not coding and unique/overlapping

```{r reference_genes}
reference_genes <- readGFF(here::here("data", "refdata-gex-GRCh38-2020-A", "genes", "genes.gtf"))
reference_genes <- unique(dplyr::select(reference_genes, gene_id, gene_type, gene_name))
```

```{r results add info gene_type}
for (i in seq_along(results)) {
  results[[i]] <- left_join(results[[i]], reference_genes, by = c("gene" = "gene_name"))
}
```

```{r results add info up_down}
for (i in seq_along(results)) {
  results[[i]]$up_down <- ifelse(
    results[[i]]$logFC > 0.5 & results[[i]]$FDR < 0.05, "Increased",
    ifelse(results[[i]]$logFC < -0.5 & results[[i]]$FDR < 0.05, "Decreased",
           "Not significant"
           )
  )
}
```

```{r results add info unique_overlapping}
for (i in seq_along(results)) {
  others_up <- unlist(lapply(signif[-i], function(df) df$gene[df$logFC > 0.5]))
  others_down <- unlist(lapply(signif[-i], function(df) df$gene[df$logFC < -0.5]))
  results[[i]]$unique_overlapping <- ifelse(
    results[[i]]$up_down == "Increased" & results[[i]]$gene %in% others_up, "Overlapping",
    ifelse(results[[i]]$up_down == "Decreased" & results[[i]]$gene %in% others_down, "Overlapping",
           ifelse(results[[i]]$up_down == "Increased" & !results[[i]]$gene %in% others_up, "Unique",
                  ifelse(results[[i]]$up_down == "Decreased" & !results[[i]]$gene %in% others_down, "Unique",
                         "Not significant"
                  )
           )
    )
  )
}
```

Volcano plots

```{r get_legend}
get_legend <- function(my_plot) {
  tmp <- ggplotGrob(my_plot)
  legend <- tmp$grobs[[which(sapply(tmp$grobs, function(x) x$name) == "guide-box")]]
  return(legend)
}
```

```{r Volcano_up_down, fig.height=9, fig.width=16}
volcano <- list()
for (i in seq_along(results)) {
  keyvals <- rep("grey", nrow(results[[i]]))
  names(keyvals) <- rep("Not significant", nrow(results[[i]]))
  
  keyvals[results[[i]]$up_down == "Increased"] <- "#A63A2A"
  names(keyvals)[keyvals == "#A63A2A"] <- "Increased"
  keyvals[results[[i]]$up_down == "Decreased"] <- "#004C8C"
  names(keyvals)[keyvals == "#004C8C"] <- "Decreased"

  volcano[[i]] <- EnhancedVolcano(results[[i]],
                  lab = results[[i]]$gene,
                  x = "logFC",
                  y = "FDR",
                  labSize = 0,
                  legendLabSize = 15,
                  titleLabSize = 16,
                  subtitleLabSize = 14,
                  axisLabSize = 12,
                  captionLabSize = 9,
                  pointSize = 1,
                  FCcutoff = 0.5,
                  pCutoff  = 0.05,
                  ylim = c(0, 3.5),
                  colAlpha = 1,
                  drawConnectors = FALSE,
                  subtitle = NULL,
                  title = names(results)[i],
                  colCustom = keyvals
  ) + theme(legend.position = "none")
  names(volcano)[i] <- names(results)[i]
}

# Extract the legend from the first plot
legend <- cowplot::get_legend(volcano[[1]] + theme(legend.position = "right"))

# Combine the individual volcano plots
combined_plot <- patchwork::wrap_plots(volcano, ncol = 5)

# Use ggdraw and draw_plot to overlay the legend in the bottom-right corner
final_plot <- cowplot::ggdraw() +
  cowplot::draw_plot(combined_plot, 0, 0, 1, 1) +    # Place the combined plot to fill the whole canvas
  cowplot::draw_plot(legend, 0.77, 0.15, 0.25, 0.25)    # Position the legend in the bottom-right

# Print the final plot
print(final_plot)
```

```{r Volcano_gene_type, fig.height=9, fig.width=16}
volcano <- list()
for (i in seq_along(results)) {
  keyvals <- rep("grey", nrow(results[[i]]))
  names(keyvals) <- rep("Not significant", nrow(results[[i]]))
  
  keyvals[results[[i]]$up_down == "Increased" & results[[i]]$gene_type == "protein_coding"] <- "#A63A2A"
  names(keyvals)[keyvals == "#A63A2A"] <- "Increased - protein coding"
  keyvals[results[[i]]$up_down == "Decreased" & results[[i]]$gene_type == "protein_coding"] <- "#004C8C"
  names(keyvals)[keyvals == "#004C8C"] <- "Decreased - protein coding"
  keyvals[results[[i]]$up_down == "Increased" & results[[i]]$gene_type == "lncRNA"] <- "#228B22"
  names(keyvals)[keyvals == "#228B22"] <- "Increased - non coding"
  keyvals[results[[i]]$up_down == "Decreased" & results[[i]]$gene_type == "lncRNA"] <- "#FFCC00"
  names(keyvals)[keyvals == "#FFCC00"] <- "Decreased - non coding"

  volcano[[i]] <- EnhancedVolcano(results[[i]],
                  lab = results[[i]]$gene,
                  x = "logFC",
                  y = "FDR",
                  labSize = 0,
                  legendLabSize = 15,
                  titleLabSize = 16,
                  subtitleLabSize = 14,
                  axisLabSize = 12,
                  captionLabSize = 9,
                  pointSize = 1,
                  FCcutoff = 0.5,
                  pCutoff  = 0.05,
                  ylim = c(0, 3.5),
                  colAlpha = 1,
                  drawConnectors = FALSE,
                  subtitle = NULL,
                  title = names(results)[i],
                  colCustom = keyvals
  ) + theme(legend.position = "none")
  names(volcano)[i] <- names(results)[i]
}

# Extract the legend from the first plot
legend <- cowplot::get_legend(volcano[[1]] + theme(legend.position = "right"))

# Combine the individual volcano plots
combined_plot <- patchwork::wrap_plots(volcano, ncol = 5)

# Use ggdraw and draw_plot to overlay the legend in the bottom-right corner
final_plot <- cowplot::ggdraw() +
  cowplot::draw_plot(combined_plot, 0, 0, 1, 1) +    # Place the combined plot to fill the whole canvas
  cowplot::draw_plot(legend, 0.77, 0.15, 0.25, 0.25)    # Position the legend in the bottom-right

# Print the final plot
print(final_plot)
```

```{r Volcano_unique_overlapping, fig.height=9, fig.width=16}
volcano <- list()
for (i in seq_along(results)) {
  keyvals <- rep("grey", nrow(results[[i]]))
  names(keyvals) <- rep("Not significant", nrow(results[[i]]))
  
  keyvals[results[[i]]$up_down == "Increased" & results[[i]]$unique_overlapping == "Unique"] <- "#A63A2A"
  names(keyvals)[keyvals == "#A63A2A"] <- "Increased - Unique"
  keyvals[results[[i]]$up_down == "Decreased" & results[[i]]$unique_overlapping == "Unique"] <- "#004C8C"
  names(keyvals)[keyvals == "#004C8C"] <- "Decreased - Unique"
  keyvals[results[[i]]$up_down == "Increased" & results[[i]]$unique_overlapping == "Overlapping"] <- "#D6A0A0"
  names(keyvals)[keyvals == "#D6A0A0"] <- "Increased - Overlapping"
  keyvals[results[[i]]$up_down == "Decreased" & results[[i]]$unique_overlapping == "Overlapping"] <- "#A0C4FF"
  names(keyvals)[keyvals == "#A0C4FF"] <- "Decreased - Overlapping"

  volcano[[i]] <- EnhancedVolcano(results[[i]],
                  lab = results[[i]]$gene,
                  x = "logFC",
                  y = "FDR",
                  labSize = 0,
                  legendLabSize = 15,
                  titleLabSize = 16,
                  subtitleLabSize = 14,
                  axisLabSize = 12,
                  captionLabSize = 9,
                  pointSize = 1,
                  FCcutoff = 0.5,
                  pCutoff  = 0.05,
                  ylim = c(0, 3.5),
                  colAlpha = 1,
                  drawConnectors = FALSE,
                  subtitle = NULL,
                  title = names(results)[i],
                  colCustom = keyvals
  ) + theme(legend.position = "none")
  names(volcano)[i] <- names(results)[i]
}

# Extract the legend from the first plot
legend <- cowplot::get_legend(volcano[[1]] + theme(legend.position = "right"))

# Combine the individual volcano plots
combined_plot <- patchwork::wrap_plots(volcano, ncol = 5)

# Use ggdraw and draw_plot to overlay the legend in the bottom-right corner
final_plot <- cowplot::ggdraw() +
  cowplot::draw_plot(combined_plot, 0, 0, 1, 1) +    # Place the combined plot to fill the whole canvas
  cowplot::draw_plot(legend, 0.77, 0.15, 0.25, 0.25)    # Position the legend in the bottom-right

# Print the final plot
print(final_plot)
```

```{r Volcano_up_down_no_lnc, fig.height=9, fig.width=16}
volcano <- list()
results_no_lnc <- results
for (i in seq_along(results)) {
  results_no_lnc[[i]] <- dplyr::filter(results_no_lnc[[i]], gene_type == "protein_coding")
  keyvals <- rep("grey", nrow(results_no_lnc[[i]]))
  names(keyvals) <- rep("Not significant", nrow(results_no_lnc[[i]]))
  
  keyvals[results_no_lnc[[i]]$up_down == "Increased" & results_no_lnc[[i]]$gene_type == "protein_coding"] <- "#A63A2A"
  names(keyvals)[keyvals == "#A63A2A"] <- "Increased - protein coding"
  keyvals[results_no_lnc[[i]]$up_down == "Decreased" & results_no_lnc[[i]]$gene_type == "protein_coding"] <- "#004C8C"
  names(keyvals)[keyvals == "#004C8C"] <- "Decreased - protein coding"

  volcano[[i]] <- EnhancedVolcano(results_no_lnc[[i]],
                  lab = results_no_lnc[[i]]$gene,
                  x = "logFC",
                  y = "FDR",
                  labSize = 0,
                  legendLabSize = 15,
                  titleLabSize = 16,
                  subtitleLabSize = 14,
                  axisLabSize = 12,
                  captionLabSize = 9,
                  pointSize = 1,
                  FCcutoff = 0.5,
                  pCutoff  = 0.05,
                  ylim = c(0, 3.5),
                  colAlpha = 1,
                  drawConnectors = FALSE,
                  subtitle = NULL,
                  title = names(results_no_lnc)[i],
                  colCustom = keyvals
  ) + theme(legend.position = "none")
  names(volcano)[i] <- names(results_no_lnc)[i]
}

# Extract the legend from the first plot
legend <- cowplot::get_legend(volcano[[1]] + theme(legend.position = "right"))

# Combine the individual volcano plots
combined_plot <- patchwork::wrap_plots(volcano, ncol = 5)

# Use ggdraw and draw_plot to overlay the legend in the bottom-right corner
final_plot <- cowplot::ggdraw() +
  cowplot::draw_plot(combined_plot, 0, 0, 1, 1) +    # Place the combined plot to fill the whole canvas
  cowplot::draw_plot(legend, 0.77, 0.15, 0.25, 0.25)    # Position the legend in the bottom-right

# Print the final plot
print(final_plot)
```

```{r Volcano_up_down_no_overlap, fig.height=9, fig.width=16}
volcano <- list()
results_no_overlap <- results
for (i in seq_along(results)) {
  results_no_overlap[[i]] <- dplyr::filter(results_no_overlap[[i]], unique_overlapping %in% c("Unique", "Not significant"))
  keyvals <- rep("grey", nrow(results_no_overlap[[i]]))
  names(keyvals) <- rep("Not significant", nrow(results_no_overlap[[i]]))
  
  keyvals[results_no_overlap[[i]]$up_down == "Increased" & results_no_overlap[[i]]$unique_overlapping == "Unique"] <- "#A63A2A"
  names(keyvals)[keyvals == "#A63A2A"] <- "Increased - Unique"
  keyvals[results_no_overlap[[i]]$up_down == "Decreased" & results_no_overlap[[i]]$unique_overlapping == "Unique"] <- "#004C8C"
  names(keyvals)[keyvals == "#004C8C"] <- "Decreased - Unique"

  volcano[[i]] <- EnhancedVolcano(results_no_overlap[[i]],
                  lab = results_no_overlap[[i]]$gene,
                  x = "logFC",
                  y = "FDR",
                  labSize = 0,
                  legendLabSize = 15,
                  titleLabSize = 16,
                  subtitleLabSize = 14,
                  axisLabSize = 12,
                  captionLabSize = 9,
                  pointSize = 1,
                  FCcutoff = 0.5,
                  pCutoff  = 0.05,
                  ylim = c(0, 3.5),
                  colAlpha = 1,
                  drawConnectors = FALSE,
                  subtitle = NULL,
                  title = names(results_no_overlap)[i],
                  colCustom = keyvals
  ) + theme(legend.position = "none")
  names(volcano)[i] <- names(results_no_overlap)[i]
}

# Extract the legend from the first plot
legend <- cowplot::get_legend(volcano[[1]] + theme(legend.position = "right"))

# Combine the individual volcano plots
combined_plot <- patchwork::wrap_plots(volcano, ncol = 5)

# Use ggdraw and draw_plot to overlay the legend in the bottom-right corner
final_plot <- cowplot::ggdraw() +
  cowplot::draw_plot(combined_plot, 0, 0, 1, 1) +    # Place the combined plot to fill the whole canvas
  cowplot::draw_plot(legend, 0.77, 0.15, 0.25, 0.25)    # Position the legend in the bottom-right

# Print the final plot
print(final_plot)
```

Bar plots

```{r signif}
signif <- results
for (i in seq_along(results)) {
  signif[[i]] <- results[[i]] %>%
    dplyr::filter(FDR < 0.05) %>%
    dplyr::filter(abs(logFC) > 0.5)
}
```

```{r Barplot_up_down, fig.height=4.5, fig.width=9}
n_de_genes <- data.frame()
for (i in seq_along(signif)) {
  cell_type <- c(rep(names(signif)[i], 2))
  effect <- c("Increased", "Decreased")
  n <- c(nrow(dplyr::filter(signif[[i]], logFC > 0)), nrow(dplyr::filter(signif[[i]], logFC < 0)))
  de_tot <- nrow(signif[[i]])
  n_de_genes <- rbind(n_de_genes, data.frame(cell_type,effect,n, de_tot))
}
n_de_genes <- n_de_genes %>%
  arrange(desc(de_tot))
n_de_genes$cell_type <- factor(n_de_genes$cell_type, levels = unique(n_de_genes$cell_type))

# Plot with customizations
ggplot(n_de_genes, aes(fill=effect, y=n, x=cell_type)) + 
  geom_bar(position="stack", stat="identity") +
  scale_fill_manual(values = c("Increased" = "#A63A2A", "Decreased" = "#004C8C")) +
  theme(text = element_text(size = 15), axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(x = "Cell Type", y = "Number of Genes", fill = "Effect") +
  guides(fill = guide_legend(title = NULL))
```

```{r Barplot_up_down_2, fig.height=4.5, fig.width=8.8}
n_de_genes <- data.frame()
for (i in seq_along(signif)) {
  cell_type <- c(rep(names(signif)[i], 2))
  effect <- c("Increased", "Decreased")
  n <- c(nrow(dplyr::filter(signif[[i]], logFC > 0)), nrow(dplyr::filter(signif[[i]], logFC < 0)))
  de_tot <- nrow(signif[[i]])
  n_de_genes <- rbind(n_de_genes, data.frame(cell_type,effect,n, de_tot))
}
n_de_genes <- n_de_genes %>%
  arrange(desc(de_tot))
n_de_genes$cell_type <- factor(n_de_genes$cell_type, levels = unique(n_de_genes$cell_type))


n_de_genes$cell_type <- gsub("_", " ", n_de_genes$cell_type)
n_de_genes$cell_type <- factor(n_de_genes$cell_type, levels = unique(n_de_genes$cell_type))

ggplot(n_de_genes, aes(fill = effect, y = n, x = cell_type)) + 
  geom_bar(position = "stack", stat = "identity") +
  scale_fill_manual(values = c("Increased" = "#A63A2A", "Decreased" = "#004C8C")) +
  theme_bw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),
    axis.text.x = element_text(angle = 30, hjust = 1, color = "black", size = 17),
    axis.text.y = element_text(color = "black", size = 17),
    axis.title.x = element_text(size = 20),
    axis.title.y = element_text(size = 20),
    text = element_text(size = 20),
    legend.text = element_text(size = 20),
    legend.title = element_blank(),
    legend.position = c(0.96, 0.9),          # Top-right inside the plot
    legend.justification = c("right", "top"), # Anchor to top-right
    legend.background = element_rect(fill = "white", color = "black") # Optional: box around legend
  ) +
  labs(x = "Cell Type", y = "Number of Genes", fill = "Effect")
```

```{r Barplot_gene_type, fig.height=4.5, fig.width=9}
n_de_genes <- data.frame()
for (i in seq_along(signif)) {
  cell_type <- names(signif)[i]
  effect <- c("Increased - protein coding", "Increased - non coding", "Decreased - protein coding", "Decreased - non coding")
  n <- c(nrow(dplyr::filter(signif[[i]], logFC > 0 & gene_type == "protein_coding")),
         nrow(dplyr::filter(signif[[i]], logFC > 0 & gene_type == "lncRNA")),
         nrow(dplyr::filter(signif[[i]], logFC < 0 & gene_type == "protein_coding")),
         nrow(dplyr::filter(signif[[i]], logFC < 0 & gene_type == "lncRNA"))
         )
  de_tot <- nrow(signif[[i]])
  n_de_genes <- rbind(n_de_genes, data.frame(cell_type,effect,n, de_tot))
}
n_de_genes$cell_type <- factor(n_de_genes$cell_type, levels = unique(n_de_genes$cell_type))

ggplot(n_de_genes, aes(fill=effect, y=n, x=cell_type)) + 
  geom_bar(position="stack", stat="identity") +
  scale_fill_manual(values = c("Increased - protein coding" = "#A63A2A", 
                               "Decreased - protein coding" = "#004C8C", 
                               "Increased - non coding" = "#D6A0A0", 
                               "Decreased - non coding" = "#A0C4FF")) +
  theme(text = element_text(size = 15), axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(x = "Cell Type", y = "Number of Genes", fill = "Effect") +
  guides(fill = guide_legend(title = NULL))
```

```{r Barplot_gene_type_2, fig.height=4.5, fig.width=8.8}
n_de_genes_nc <- data.frame()
for (i in seq_along(signif)) {
  cell_type <- names(signif)[i]
  effect <- c("Increased - protein coding", "Increased - non coding", "Decreased - protein coding", "Decreased - non coding")
  n <- c(nrow(dplyr::filter(signif[[i]], logFC > 0 & gene_type == "protein_coding")),
         nrow(dplyr::filter(signif[[i]], logFC > 0 & gene_type == "lncRNA")),
         nrow(dplyr::filter(signif[[i]], logFC < 0 & gene_type == "protein_coding")),
         nrow(dplyr::filter(signif[[i]], logFC < 0 & gene_type == "lncRNA"))
         )
  de_tot <- nrow(signif[[i]])
  n_de_genes_nc <- rbind(n_de_genes_nc, data.frame(cell_type,effect,n, de_tot))
}

# Clean up cell type names
n_de_genes_nc$cell_type <- gsub("_", " ", n_de_genes_nc$cell_type)
n_de_genes_nc$cell_type <- factor(n_de_genes_nc$cell_type, levels = c("Cardiomyocytes",
                                                                    "Fibroblasts",
                                                                    "Endothelial cells",
                                                                    "Pericytes",
                                                                    "Macrophages",
                                                                    "Smooth muscle cells",
                                                                    "T lymphocytes",
                                                                    "Neuronal cells",
                                                                    "Endocardial cells"
                                                                    ))


# Plot
ggplot(n_de_genes_nc, aes(fill = effect, y = n, x = cell_type)) + 
  geom_bar(position = "stack", stat = "identity") +
  scale_fill_manual(values = c("Increased - protein coding" = "#E76F51", 
                               "Decreased - protein coding" = "#264653", 
                               "Increased - non coding" = "#F4A261", 
                               "Decreased - non coding" = "#2A9D8F"
  )) +
  theme_bw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),
    axis.text.x = element_text(angle = 30, hjust = 1, color = "black", size = 17),
    axis.text.y = element_text(color = "black", size = 17),
    axis.title.x = element_text(size = 20),
    axis.title.y = element_text(size = 20),
    text = element_text(size = 20),
    legend.text = element_text(size = 20),
    legend.title = element_blank(),
    legend.position = c(0.96, 0.9),
    legend.justification = c("right", "top"),
    legend.background = element_rect(fill = "white", color = "black")
  ) +
  labs(x = "Cell Type", y = "Number of Genes", fill = "Effect")
```

```{r Barplot_gene_type_3, fig.height=4.5, fig.width=9}
n_de_genes_u<- data.frame()
for (i in seq_along(signif)) {
  cell_type <- names(signif)[i]
  effect <- c("Increased - Unique", "Increased - Overlapping", "Decreased - Unique", "Decreased - Overlapping")
  n <- c(nrow(dplyr::filter(signif[[i]], logFC > 0 & unique_overlapping == "Unique")),
         nrow(dplyr::filter(signif[[i]], logFC > 0 & unique_overlapping == "Overlapping")),
         nrow(dplyr::filter(signif[[i]], logFC < 0 & unique_overlapping == "Unique")),
         nrow(dplyr::filter(signif[[i]], logFC < 0 & unique_overlapping == "Overlapping"))
         )
  de_tot <- nrow(signif[[i]])
  n_de_genes_u <- rbind(n_de_genes_u, data.frame(cell_type,effect,n, de_tot))
}

# Clean up cell type names
n_de_genes_u$cell_type <- gsub("_", " ", n_de_genes_u$cell_type)
n_de_genes_u$cell_type <- factor(n_de_genes_u$cell_type, levels = c("Cardiomyocytes",
                                                                    "Fibroblasts",
                                                                    "Endothelial cells",
                                                                    "Pericytes",
                                                                    "Smooth muscle cells",
                                                                    "Macrophages",
                                                                    "Neuronal cells",
                                                                    "Lymphocytes",
                                                                    "Endocardial cells"
                                                                    ))

# Set output file path
output_file <- file.path(output_dir_data, "Barplot_protein_overlapping_poster.png")

# Save plot to PNG
png(output_file, width = 8.8, height = 4.5, units = "in", res = 300)

# Plot
ggplot(n_de_genes_u, aes(fill = effect, y = n, x = cell_type)) + 
  geom_bar(position = "stack", stat = "identity") +
  scale_fill_manual(values = c("Increased - Unique" = "#A63A2A", 
                               "Decreased - Unique" = "#004C8C", 
                               "Increased - Overlapping" = "#D6A0A0", 
                               "Decreased - Overlapping" = "#A0C4FF"
  )) +
  theme_bw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),
    axis.text.x = element_text(angle = 30, hjust = 1, color = "black", size = 17),
    axis.text.y = element_text(color = "black", size = 17),
    axis.title.x = element_text(size = 20),
    axis.title.y = element_text(size = 20),
    text = element_text(size = 20),
    legend.text = element_text(size = 20),
    legend.title = element_blank(),
    legend.position = c(0.96, 0.9),
    legend.justification = c("right", "top"),
    legend.background = element_rect(fill = "white", color = "black")
  ) +
  labs(x = "Cell Type", y = "Number of Genes", fill = "Effect")

dev.off()
```

```{r Barplot_up_down_unique_overlapping, fig.height=4.5, fig.width=9}
n_de_genes<- data.frame()
for (i in seq_along(signif)) {
  cell_type <- names(signif)[i]
  effect <- c("Increased - Unique", "Increased - Overlapping", "Decreased - Unique", "Decreased - Overlapping")
  n <- c(nrow(dplyr::filter(signif[[i]], logFC > 0 & unique_overlapping == "Unique")),
         nrow(dplyr::filter(signif[[i]], logFC > 0 & unique_overlapping == "Overlapping")),
         nrow(dplyr::filter(signif[[i]], logFC < 0 & unique_overlapping == "Unique")),
         nrow(dplyr::filter(signif[[i]], logFC < 0 & unique_overlapping == "Overlapping"))
         )
  de_tot <- nrow(signif[[i]])
  n_de_genes <- rbind(n_de_genes, data.frame(cell_type,effect,n, de_tot))
}
n_de_genes$cell_type <- factor(n_de_genes$cell_type, levels = unique(n_de_genes$cell_type))

ggplot(n_de_genes, aes(fill=effect, y=n, x=cell_type)) + 
  geom_bar(position="stack", stat="identity") +
  scale_fill_manual(values = c("Increased - Unique" = "#E76F51", 
                               "Decreased - Unique" = "#264653", 
                               "Increased - Overlapping" = "#F4A261", 
                               "Decreased - Overlapping" = "#2A9D8F")) +
  theme(text = element_text(size = 15), axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(x = "Cell Type", y = "Number of Genes", fill = "Effect") +
  guides(fill = guide_legend(title = NULL))
```

```{r Barplot_unique_overlapping, fig.height=4.5, fig.width=9}
n_de_genes<- data.frame()
for (i in seq_along(signif)) {
  cell_type <- names(signif)[i]
  effect <- c("Unique", "Overlapping")
  n <- c(nrow(dplyr::filter(signif[[i]], unique_overlapping == "Unique")),
         nrow(dplyr::filter(signif[[i]], unique_overlapping == "Overlapping"))
         )
  de_tot <- nrow(signif[[i]])
  n_de_genes <- rbind(n_de_genes, data.frame(cell_type,effect,n, de_tot))
}
n_de_genes$cell_type <- factor(n_de_genes$cell_type, levels = unique(n_de_genes$cell_type))

ggplot(n_de_genes, aes(fill=effect, y=n, x=cell_type)) + 
  geom_bar(position="stack", stat="identity") +
  scale_fill_manual(values = c("Unique" = "#A63A2A", 
                               "Overlapping" = "#004C8C")) +
  theme(text = element_text(size = 15), axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(x = "Cell Type", y = "Number of Genes", fill = "Effect") +
  guides(fill = guide_legend(title = NULL))
```

UpSet plots

```{r signif_up_down}
signif_up <- signif
for (i in seq_along(signif_up)) {
  signif_up[[i]] <- filter(signif_up[[i]], logFC > 0)
}

signif_down <- signif
for (i in seq_along(signif_down)) {
  signif_down[[i]] <- filter(signif_down[[i]], logFC < 0)
}

```

```{r UpSet_plot_mPAP, fig.height=8, fig.width=12}
gene_sets <- list()
for (i in seq_along(signif_up)) {
  gene_sets[[i]] <- signif_up[[i]]$gene
  names(gene_sets)[i] <- names(signif_up)[i]
  }
m <- make_comb_mat(gene_sets, mode = "distinct", min_set_size = 10)
#m <- m[comb_degree(m) >= 2]
m <- m[comb_size(m) >= 10]
p1 <- UpSet(m, column_title = "DE mPAP_mmHg - Upregulated", comb_order = order(comb_size(m)), 
                    top_annotation = upset_top_annotation(m, add_numbers = TRUE),
                    right_annotation = upset_right_annotation(m, add_numbers = TRUE))
gene_sets <- list()
for (i in seq_along(signif_down)) {
  gene_sets[[i]] <- signif_down[[i]]$gene
  names(gene_sets)[i] <- names(signif_down)[i]
  }
m <- make_comb_mat(gene_sets, mode = "distinct", min_set_size = 10)
#m <- m[comb_degree(m) >= 2]
m <- m[comb_size(m) >= 10]
p2 <- UpSet(m, column_title = "DE mPAP_mmHg - Downregulated", comb_order = order(comb_size(m)), 
                    top_annotation = upset_top_annotation(m, add_numbers = TRUE),
                    right_annotation = upset_right_annotation(m, add_numbers = TRUE))

p1 <- grid::grid.grabExpr(draw(p1))
p2 <- grid::grid.grabExpr(draw(p2))

combined_plots <- plot_grid(p1, p2, ncol = 1)

print(combined_plots)
rm(gene_sets, m, p1, p2, combined_plots)
```


## GSEA

```{r reorder_GO_by_pvalue}
reorder_GO_by_pvalue <- function(enrichGO_result) {
  go_results <- enrichGO_result@result
  go_results_sorted <- go_results[order(go_results$p.adjust), ]
  enrichGO_result@result <- go_results_sorted
  return(enrichGO_result)
}
```

```{r classify_terms}
classify_terms <- function(df) {
  df$sign <- ifelse(df$NES > 0, "activated", "suppressed")
  return(df)
}
```

```{r cluster_names_2}
cluster_names_2 <- c("Cardiomyocytes", "Fibroblasts", "Endothelial cells", "Pericytes", "Macrophages", "T lymphocytes", "Smooth muscle cells", "Neuronal cells", "Endocardial cells")
```


```{r GSEA_all, eval=FALSE}
ranked_genes <- list()
GSEA_all <- list()
for (i in seq_along(cluster_names)) {
  gene_counts <- rowSums(subset(DCM_RV_integrated, cell_type == cluster_names_2[i])@assays$RNA@counts > 0)
  universe_genes <- names(gene_counts[gene_counts >= 3])
  write.csv(as.data.frame(universe_genes), here::here(output_dir_data, paste0(cluster_names[i], "_universe_genes.csv")), quote=F, row.names = F)
  universe_entrez <- bitr(universe_genes, fromType = "SYMBOL", toType = "ENTREZID", OrgDb = org.Hs.eg.db)$ENTREZID
  write.csv(as.data.frame(universe_entrez), here::here(output_dir_data, paste0(cluster_names[i], "_universe_entrez.csv")), quote=F, row.names = F)
  rm(gene_counts)
  
  up_genes <- filter(signif[[i]], logFC > 0.5)$gene
  up_genes <- bitr(up_genes, fromType="SYMBOL", toType="ENTREZID", OrgDb="org.Hs.eg.db")$ENTREZID
  down_genes <- filter(signif[[i]], logFC < -0.5)$gene
  down_genes <- bitr(down_genes, fromType="SYMBOL", toType="ENTREZID", OrgDb="org.Hs.eg.db")$ENTREZID
  
  ranked_genes[[i]] <- results[[i]]
  names(ranked_genes)[i] <- cluster_names[i]
  ranked_genes[[i]]$metric <- ranked_genes[[i]]$logFC*-log10(ranked_genes[[i]]$PValue)
  entrezid <- bitr(ranked_genes[[i]]$gene, fromType="SYMBOL", toType="ENTREZID", OrgDb="org.Hs.eg.db", drop = TRUE)
  ranked_genes[[i]] <- merge(ranked_genes[[i]], entrezid, by.x = "gene", by.y = "SYMBOL")
  ranked_genes[[i]] <- ranked_genes[[i]][!duplicated(ranked_genes[[i]]$metric), ]
  write.csv(ranked_genes[[i]], file = here::here(output_dir_data, paste0(cluster_names[i], "_ranked_genes.csv")), quote=F, row.names = F)
  
  genelist <- ranked_genes[[i]]$metric
  names(genelist) <- ranked_genes[[i]]$ENTREZID
  genelist <- genelist[order(genelist, decreasing = T)]
  
  GSEA_all[i] <- gseGO(geneList = genelist,
                       OrgDb = org.Hs.eg.db,
                       ont = "ALL",
                       keyType = "ENTREZID",
                       nPermSimple = 1000000,
                       minGSSize = 10,
                       eps = 0)
  GSEA_all[[i]] <- reorder_GO_by_pvalue(GSEA_all[[i]])
  names(GSEA_all)[i] <- cluster_names[i]
  saveRDS(GSEA_all[i], here::here(output_dir_data, paste0(cluster_names[i], "_GSEA_GO_mPAP.rds")))
}

rm(universe_genes, universe_entrez, up_genes, down_genes, genelist)

saveRDS(ranked_genes, here::here(output_dir_data, "ranked_genes_list.rds"))
saveRDS(GSEA_all, here::here(output_dir_data, "GSEA_all_list.rds"))
```

```{r load GSEA_all}
GSEA_all <- readRDS(here::here(output_dir_data, "GSEA_all_list.rds"))
```

```{r GSEA_Cardiomyocytes, fig.height=8, fig.width=8}
GSEA_simplified <- clusterProfiler::simplify(
  GSEA_all[["Cardiomyocytes"]],
  cutoff = 0.75,
  by = "p.adjust",
  select_fun = min,
  measure = "Wang",
  semData = NULL
)

GSEA_simplified <- reorder_GO_by_pvalue(GSEA_simplified)

dotplot(GSEA_simplified, showCategory = 8, split=".sign", title = paste0("Cardiomyocytes", "\nGO Enrichment Analysis", "\nmPAP-associated genes"), 
        label_format = 35, font.size = 15) +
  theme(plot.title = element_text( face = "bold", size = 18, hjust = 0.5),
        axis.text.y = element_text(face = "bold"),
        strip.text = element_text(face = "bold", size = 18)) +
  facet_grid(.~.sign)
```

```{r GSEA_Cardiomyocytes_emapplot, fig.height=10, fig.width=20}
GSEA_simplified@result <- classify_terms(GSEA_simplified@result)

activated_terms <- subset(GSEA_simplified@result, sign == "activated")
suppressed_terms <- subset(GSEA_simplified@result, sign == "suppressed")

GSEA_activated <- GSEA_simplified
GSEA_activated@result <- activated_terms
GSEA_activated <- pairwise_termsim(GSEA_activated)

GSEA_suppressed <- GSEA_simplified
GSEA_suppressed@result <- suppressed_terms
GSEA_suppressed <- pairwise_termsim(GSEA_suppressed)

p1 <- emapplot(GSEA_activated, showCategory = 100, size_category = 0.7, min_edge = 0.15) +
  ggtitle("Activated Terms") +
  theme(plot.title = element_text(face = "bold", size = 18, hjust = 0.5))

p2 <- emapplot(GSEA_suppressed, showCategory = 100, size_category = 0.7, min_edge = 0.15) +
  ggtitle("Suppressed Terms") +
  theme(plot.title = element_text(face = "bold", size = 18, hjust = 0.5))

combined_plot <- p1 | p2
print(combined_plot)
rm(GSEA_simplified, activated_terms, suppressed_terms, GSEA_activated, GSEA_suppressed, p1, p2)
```

```{r GSEA_Fibroblasts, fig.height=8, fig.width=8}
GSEA_simplified <- clusterProfiler::simplify(
  GSEA_all[["Fibroblasts"]],
  cutoff = 0.75,
  by = "p.adjust",
  select_fun = min,
  measure = "Wang",
  semData = NULL
)

GSEA_simplified <- reorder_GO_by_pvalue(GSEA_simplified)

dotplot(GSEA_simplified, showCategory = 8, split=".sign", title = paste0("Fibroblasts", "\nGO Enrichment Analysis", "\nmPAP-associated genes"), 
        label_format = 30, font.size = 15) +
  theme(plot.title = element_text( face = "bold", size = 18, hjust = 0.5),
        axis.text.y = element_text(face = "bold"),
        strip.text = element_text(face = "bold", size = 18)) +
  facet_grid(.~.sign)
```

```{r GSEA_Fibroblasts_emapplot, fig.height=10, fig.width=10}
GSEA_simplified@result <- classify_terms(GSEA_simplified@result)

activated_terms <- subset(GSEA_simplified@result, sign == "activated")
suppressed_terms <- subset(GSEA_simplified@result, sign == "suppressed")

GSEA_activated <- GSEA_simplified
GSEA_activated@result <- activated_terms
GSEA_activated <- pairwise_termsim(GSEA_activated)

GSEA_suppressed <- GSEA_simplified
GSEA_suppressed@result <- suppressed_terms

p1 <- emapplot(GSEA_activated, showCategory = 100, size_category = 0.7, min_edge = 0.15) +
  ggtitle("Activated Terms") +
  theme(plot.title = element_text(face = "bold", size = 18, hjust = 0.5))

combined_plot <- p1 
print(combined_plot)
rm(GSEA_simplified, activated_terms, suppressed_terms, GSEA_activated, GSEA_suppressed, p1, p2)
```

```{r GSEA_Endothelial_cells, fig.height=8, fig.width=8}
GSEA_simplified <- clusterProfiler::simplify(
  GSEA_all[["Endothelial_cells"]],
  cutoff = 0.75,
  by = "p.adjust",
  select_fun = min,
  measure = "Wang",
  semData = NULL
)

GSEA_simplified <- reorder_GO_by_pvalue(GSEA_simplified)

dotplot(GSEA_simplified, showCategory = 8, split=".sign", title = paste0("Endothelial cells", "\nGO Enrichment Analysis", "\nmPAP-associated genes"), 
        label_format = 40, font.size = 15) +
  theme(plot.title = element_text( face = "bold", size = 18, hjust = 0.5),
        axis.text.y = element_text(face = "bold"),
        strip.text = element_text(face = "bold", size = 18)) +
  facet_grid(.~.sign)
```

```{r GSEA_Endothelial_cells_emapplot, fig.height=10, fig.width=20}
GSEA_simplified@result <- classify_terms(GSEA_simplified@result)

activated_terms <- subset(GSEA_simplified@result, sign == "activated")
suppressed_terms <- subset(GSEA_simplified@result, sign == "suppressed")

GSEA_activated <- GSEA_simplified
GSEA_activated@result <- activated_terms
GSEA_activated <- pairwise_termsim(GSEA_activated)

GSEA_suppressed <- GSEA_simplified
GSEA_suppressed@result <- suppressed_terms
GSEA_suppressed <- pairwise_termsim(GSEA_suppressed)

p1 <- emapplot(GSEA_activated, showCategory = 100, size_category = 0.7, min_edge = 0.15) +
  ggtitle("Activated Terms") +
  theme(plot.title = element_text(face = "bold", size = 18, hjust = 0.5))

p2 <- emapplot(GSEA_suppressed, showCategory = 100, size_category = 0.7, min_edge = 0.15) +
  ggtitle("Suppressed Terms") +
  theme(plot.title = element_text(face = "bold", size = 18, hjust = 0.5))

combined_plot <- p1 | p2
print(combined_plot)
rm(GSEA_simplified, activated_terms, suppressed_terms, GSEA_activated, GSEA_suppressed, p1, p2)
```

```{r GSEA_Pericytes, fig.height=8, fig.width=8}
GSEA_simplified <- clusterProfiler::simplify(
  GSEA_all[["Pericytes"]],
  cutoff = 0.75,
  by = "p.adjust",
  select_fun = min,
  measure = "Wang",
  semData = NULL
)

GSEA_simplified <- reorder_GO_by_pvalue(GSEA_simplified)

dotplot(GSEA_simplified, showCategory = 8, split=".sign", title = paste0("Pericytes", "\nGO Enrichment Analysis", "\nmPAP-associated genes"), 
        label_format = 30, font.size = 15) +
  theme(plot.title = element_text( face = "bold", size = 18, hjust = 0.5),
        axis.text.y = element_text(face = "bold"),
        strip.text = element_text(face = "bold", size = 18)) +
  facet_grid(.~.sign)
```

```{r GSEA_Pericytes_emapplot, fig.height=10, fig.width=20}
GSEA_simplified@result <- classify_terms(GSEA_simplified@result)

activated_terms <- subset(GSEA_simplified@result, sign == "activated")
suppressed_terms <- subset(GSEA_simplified@result, sign == "suppressed")

GSEA_activated <- GSEA_simplified
GSEA_activated@result <- activated_terms
GSEA_activated <- pairwise_termsim(GSEA_activated)

GSEA_suppressed <- GSEA_simplified
GSEA_suppressed@result <- suppressed_terms
GSEA_suppressed <- pairwise_termsim(GSEA_suppressed)

p1 <- emapplot(GSEA_activated, showCategory = 100, size_category = 0.7, min_edge = 0.15) +
  ggtitle("Activated Terms") +
  theme(plot.title = element_text(face = "bold", size = 18, hjust = 0.5))

p2 <- emapplot(GSEA_suppressed, showCategory = 100, size_category = 0.7, min_edge = 0.15) +
  ggtitle("Suppressed Terms") +
  theme(plot.title = element_text(face = "bold", size = 18, hjust = 0.5))

combined_plot <- p1 | p2
print(combined_plot)
rm(GSEA_simplified, activated_terms, suppressed_terms, GSEA_activated, GSEA_suppressed, p1, p2)
```

```{r GSEA_Macrophages, fig.height=8, fig.width=8}
GSEA_simplified <- clusterProfiler::simplify(
  GSEA_all[["Macrophages"]],
  cutoff = 0.75,
  by = "p.adjust",
  select_fun = min,
  measure = "Wang",
  semData = NULL
)

GSEA_simplified <- reorder_GO_by_pvalue(GSEA_simplified)

dotplot(GSEA_simplified, showCategory = 8, split=".sign", title = paste0("Macrophages", "\nGO Enrichment Analysis", "\nmPAP-associated genes"), 
        label_format = 30, font.size = 15) +
  theme(plot.title = element_text( face = "bold", size = 18, hjust = 0.5),
        axis.text.y = element_text(face = "bold"),
        strip.text = element_text(face = "bold", size = 18)) +
  facet_grid(.~.sign)
```

```{r GSEA_Macrophages_emapplot, fig.height=10, fig.width=20}
GSEA_simplified@result <- classify_terms(GSEA_simplified@result)

activated_terms <- subset(GSEA_simplified@result, sign == "activated")
suppressed_terms <- subset(GSEA_simplified@result, sign == "suppressed")

GSEA_activated <- GSEA_simplified
GSEA_activated@result <- activated_terms
GSEA_activated <- pairwise_termsim(GSEA_activated)

GSEA_suppressed <- GSEA_simplified
GSEA_suppressed@result <- suppressed_terms
GSEA_suppressed <- pairwise_termsim(GSEA_suppressed)

p1 <- emapplot(GSEA_activated, showCategory = 100, size_category = 0.7, min_edge = 0.15) +
  ggtitle("Activated Terms") +
  theme(plot.title = element_text(face = "bold", size = 18, hjust = 0.5))

p2 <- emapplot(GSEA_suppressed, showCategory = 100, size_category = 0.7, min_edge = 0.15) +
  ggtitle("Suppressed Terms") +
  theme(plot.title = element_text(face = "bold", size = 18, hjust = 0.5))

combined_plot <- p1 | p2
print(combined_plot)
rm(GSEA_simplified, activated_terms, suppressed_terms, GSEA_activated, GSEA_suppressed, p1, p2)
```

```{r GSEA_Lymphocytes, fig.height=8, fig.width=8}
GSEA_simplified <- clusterProfiler::simplify(
  GSEA_all[["T_lymphocytes"]],
  cutoff = 0.75,
  by = "p.adjust",
  select_fun = min,
  measure = "Wang",
  semData = NULL
)

GSEA_simplified <- reorder_GO_by_pvalue(GSEA_simplified)

dotplot(GSEA_simplified, showCategory = 8, split=".sign", title = paste0("T Lymphocytes", "\nGO Enrichment Analysis", "\nmPAP-associated genes"), 
        label_format = 30, font.size = 15) +
  theme(plot.title = element_text( face = "bold", size = 18, hjust = 0.5),
        axis.text.y = element_text(face = "bold"),
        strip.text = element_text(face = "bold", size = 18)) +
  facet_grid(.~.sign)
```

```{r GSEA_Lymphocytes_emapplot, fig.height=10, fig.width=10}
GSEA_simplified@result <- classify_terms(GSEA_simplified@result)

activated_terms <- subset(GSEA_simplified@result, sign == "activated")

GSEA_activated <- GSEA_simplified
GSEA_activated@result <- activated_terms
GSEA_activated <- pairwise_termsim(GSEA_activated)

p1 <- emapplot(GSEA_activated, showCategory = 100, size_category = 0.7, min_edge = 0.15) +
  ggtitle("Activated Terms") +
  theme(plot.title = element_text(face = "bold", size = 18, hjust = 0.5))

print(p1)
rm(GSEA_simplified, activated_terms, suppressed_terms, GSEA_activated, GSEA_suppressed, p1, p2)
```


## NES plot

```{r default_labeller}
default_labeller <- function(n) {
    function(str){
        str <- gsub("_", " ", str)
        ep_str_wrap(str, n)
    }
}
```

```{r ep_str_wrap}
ep_str_wrap <- function(string, width) {
    x <- gregexpr(' ', string)
    vapply(seq_along(x),
           FUN = function(i) {
               y <- x[[i]]
               n <- nchar(string[i])
               len <- (c(y,n) - c(0, y)) ## length + 1
               idx <- len > width
               j <- which(!idx)
               if (length(j) && max(j) == length(len)) {
                   j <- j[-length(j)]
               }
               if (length(j)) {
                   idx[j] <- len[j] + len[j+1] > width
               }
               idx <- idx[-length(idx)] ## length - 1
               start <- c(1, y[idx] + 1)
               end <- c(y[idx] - 1, n)
               words <- substring(string[i], start, end)
               paste0(words, collapse="\n")
           },
           FUN.VALUE = character(1)
    )
}
```

```{r, fig.height=12, fig.width=6}
GSEA_all <- readRDS(here::here(output_dir_data, "GSEA_all_list.rds"))

cell_order <- c(
  "Fibroblasts", "Endothelial_cells", "Pericytes", "Macrophages",
  "T_lymphocytes", "Smooth_muscle_cells", "Neuronal_cells", "Endocardial_cells"
)

top_n_pos <- 4
top_n_neg <- 4
padj_cutoff <- 0.05

library(dplyr)
library(tibble)
library(ggplot2)
library(stringr)
library(scales)

wrap_2lines <- function(x, width = 35) {
  vapply(x, function(s) {
    s <- as.character(s)
    if (nchar(s) <= width) return(s)

    cut <- str_locate_all(substr(s, 1, width), " ")[[1]]
    cut <- if (nrow(cut) == 0) width else max(cut[, 1])

    line1 <- str_trim(substr(s, 1, cut))
    rest  <- str_trim(substr(s, cut + 1, nchar(s)))

    if (nchar(rest) > width) rest <- paste0(substr(rest, 1, width - 1), "…")
    paste(line1, rest, sep = "\n")
  }, FUN.VALUE = character(1))
}

df_gsea <- lapply(cell_order, function(ct) {

  obj <- GSEA_all[[ct]]
  if (is.null(obj) || nrow(obj@result) == 0) return(NULL)

  obj_simpl <- clusterProfiler::simplify(
    obj,
    cutoff = 0.6,
    by = "p.adjust",
    select_fun = min,
    measure = "Wang",
    semData = NULL
  )

  res <- obj_simpl@result %>%
    as_tibble() %>%
    mutate(cell_type = ct) %>%
    filter(!is.na(NES), !is.na(p.adjust)) %>%
    filter(p.adjust < padj_cutoff)

  if (nrow(res) == 0) return(NULL)

  pos <- res %>%
    filter(NES > 0) %>%
    arrange(desc(NES)) %>%
    slice_head(n = top_n_pos)

  neg <- res %>%
    filter(NES < 0) %>%
    arrange(NES) %>%
    slice_head(n = top_n_neg)

  bind_rows(pos, neg)
}) %>% bind_rows()

if (nrow(df_gsea) == 0) {
  message("No significant terms (p.adjust < ", padj_cutoff, ") found.")
} else {

  # color score like the example: -log10(p) * sign(NES)
  # use pvalue if present; otherwise fall back to p.adjust
  df_gsea <- df_gsea %>%
    mutate(
      p_for_color = if ("pvalue" %in% colnames(.)) pvalue else p.adjust,
      score = -log10(p_for_color) * sign(NES),
      cell_type = factor(cell_type, levels = cell_order),
      desc_id = paste(cell_type, Description, sep = "___")
    )

  # order terms within each cell type by NES (neg -> pos)
  desc_levels <- df_gsea %>%
    arrange(cell_type, NES) %>%
    pull(desc_id)

  df_gsea$desc_id <- factor(df_gsea$desc_id, levels = unique(desc_levels))

  # make the diverging scale readable even if up-terms have higher p-values:
  # cap extremes using a high quantile so mid-range differences stay visible
  L <- unname(quantile(abs(df_gsea$score), probs = 0.80, na.rm = TRUE))
  if (!is.finite(L) || L == 0) L <- max(abs(df_gsea$score), na.rm = TRUE)

  ggplot(df_gsea, aes(x = desc_id, y = NES, fill = score)) +
    geom_col(width = 0.9) +
    facet_grid(
      cell_type ~ .,
      scales = "free_y", space = "free_y", switch = "y",
      labeller = labeller(cell_type = function(x) gsub("_", " ", x))
    ) +
    scale_fill_gradient2(
      low = "#004C8C",
      mid = "white",
      high = "#A63A2A",
      midpoint = 0,
      limits = c(-L, L),
      oob = scales::squish,
      name = expression(-log[10](p) %*% sign(NES))
    ) +
    scale_x_discrete(labels = function(x) {
      term <- sub("^.*___", "", x)
      wrap_2lines(term, width = 37)
    }) +
    coord_flip() +
    labs(x = NULL, y = "Normalized enrichment score (NES)") +
    theme_bw(base_size = 10) +
    theme(
      text = element_text(color = "black"),
      axis.text = element_text(color = "black"),
      axis.title = element_text(color = "black", size = 14),
      plot.title = element_blank(),
      axis.text.y = element_text(size = 10.2),
      strip.background = element_blank(),
      strip.placement = "outside",
      strip.text.y.left = element_text(angle = 90, face = "bold", size = 13, color = "black"),
      panel.spacing.y = unit(0.6, "lines"),
      legend.position = "bottom",
      legend.direction = "horizontal",
     legend.title = element_text(size = 9),
     legend.text = element_text(size = 9)
    ) + 
    guides(fill = guide_colorbar(
    barwidth  = unit(6, "cm"),
    barheight = unit(0.3, "cm"),
    title.position = "top",
    title.hjust = 0.5
  ))
}
```






